// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp6OJvgwgKm_1MHfuIMZyEeM_cKbIAWAg',
    appId: '1:966815768056:web:64b78f306ed0e5403e8a0d',
    messagingSenderId: '966815768056',
    projectId: 'ijgo-6492a',
    authDomain: 'ijgo-6492a.firebaseapp.com',
    storageBucket: 'ijgo-6492a.firebasestorage.app',
    measurementId: 'G-JXWYP16DFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqBVz8IfFXJiQppYHjmb60Qi2PgQC7b4A',
    appId: '1:966815768056:android:9ec928e0ecf0e79a3e8a0d',
    messagingSenderId: '966815768056',
    projectId: 'ijgo-6492a',
    storageBucket: 'ijgo-6492a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqXTHD5Xq7GdtroNKYFXtk849azYJt4uY',
    appId: '1:966815768056:ios:7f4331227230ae383e8a0d',
    messagingSenderId: '966815768056',
    projectId: 'ijgo-6492a',
    storageBucket: 'ijgo-6492a.firebasestorage.app',
    iosBundleId: 'ua.germes.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqXTHD5Xq7GdtroNKYFXtk849azYJt4uY',
    appId: '1:966815768056:ios:7f4331227230ae383e8a0d',
    messagingSenderId: '966815768056',
    projectId: 'ijgo-6492a',
    storageBucket: 'ijgo-6492a.firebasestorage.app',
    iosBundleId: 'ua.germes.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp6OJvgwgKm_1MHfuIMZyEeM_cKbIAWAg',
    appId: '1:966815768056:web:f35b86400fee98313e8a0d',
    messagingSenderId: '966815768056',
    projectId: 'ijgo-6492a',
    authDomain: 'ijgo-6492a.firebaseapp.com',
    storageBucket: 'ijgo-6492a.firebasestorage.app',
    measurementId: 'G-6GG44DDX8E',
  );
}
